version: "3.7"
services:
  gql:
    build: .
    command: yarn start
    ports:
      - 4000:4000
    depends_on:
      - neo
  neo:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_data:/data/
    env_file:
      - .env.neo4j
volumes:
  neo4j_data:
